name: LuaLlamas
main: com.hk.spigot.LuaLlamas
version: 1.1
api-version: 1.13
commands:
   lua:
      description: Run some lua code...
      usage: /lua <code>
      permission: com.hk.spigot.luacommand